### ISSUE TITLE
Demo page not working?

### ISSUE THREAD

**Issue by mrange** [erossini/BlazorClippy#1]
Hi.

I just want to make you aware it seems the demo page doesn't seem to be working.

**Comment by erossini** [comment]
Yes, you are right. The JavaScript reads the images and sounds from `s3.amazon.com` and the author removed those files from it. So, the clippy is not working.

I'll try to fix it.

**Comment by erossini** [comment]
With the [new version](https://www.nuget.org/packages/PSC.Blazor.Components.Clippy/1.0.6) of the component, the issue is solved. All the images and sounds are coming from the component itself.

**Comment by wortelus** [comment]
Are the agents besides Clippy missing though ? I am only finding the files for Clippy in the repo :)
